version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        container_name: chapter-user-project-app
        restart: unless-stopped
        volumes:
            - ./:/app
            - ./etc/docker/nginx/default.conf:/etc/nginx/http.d/default.conf
            - ./etc/docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./etc/docker/supervisord.conf:/etc/supervisord.conf
        ports:
            - '${APP_PORT:-8080}:8080'
        networks:
            - chapter-net
    mongo:
        image: "mongo:5.0"
        container_name: chapter-user-project-mongo
        command: mongod --auth
        restart: unless-stopped
        logging:
            driver: none
        ports:
            - "${SERVER_MONGO_DB_EXPOSE_SERVICE:-27017}:${DB_PORT:-27017}"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - /home/$USER/chapter-user-project/mongo-data:/data/db
            - /home/$USER/chapter-user-project/mongo-log:/var/log/mongodb/
        networks:
            - chapter-net
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${DB_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mongo
        networks:
            - chapter-net
        ports:
            - '${FORWARD_MONGODB_EXPRESS_PORT:-8081}:8081'
        healthcheck:
            test: wget --quiet --tries=3 --spider http://${DB_USERNAME}:${DB_PASSWORD}@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
networks:
    chapter-net:
        external:
            name: chapter-network
